# Generated by Django 3.0.3 on 2020-03-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pict',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
