# Generated by Django 3.0.3 on 2020-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customer_profile_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pict',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
